### ISSUE TITLE
Close Order Form

### ISSUE THREAD

**Issue by jgramirez0210** [NSS-Evening-25-Cohort/pos-system-e25-rage-committers#16]
- [x] Payment Type - Drop Down
- [x] Tip Amount 
- [x] Close Order Button

**Comment by tatianabarga** [comment]
inputs:

- [ ] payment type (cash, check, debit, credit, or mobile payment dropdown)
- [ ] tip amount
- [ ] submit button (changes status from open to closed & creates new revenue node)
