### ISSUE TITLE
Close Order Button

### ISSUE THREAD

**Issue by jgramirez0210** [NSS-Evening-25-Cohort/pos-system-e25-rage-committers#22]
As an authenticated user, when I submit the Close Order form, the order's status should change from "Open" to "Closed".

**Comment by tatianabarga** [comment]
- [ ] on all orders on view orders screen
- [ ] takes user to close order form

**Comment by tatianabarga** [comment]
- [ ] create button
- [ ] create event listener
- [ ] create function
